dist: trusty
sudo: true

jobs:
  include:
    - stage: build
      script: docker -it --rm -w /src -v $PWD/go-src:/src -v /go:/go golang go build -v ./...
    - stage: test
      script: docker -it --rm -w /src -v $PWD/go-src:/src -v /go:/go golang go test -v ./...