dist: trusty
sudo: true

cache:
  directories:
    - $HOME/go

jobs:
  include:
    - stage: build
      name: 'go'
      script: |
        docker run -it --rm \
          --workdir /src \
          --volume $PWD/go-src:/src \
          --volume /go:/go \
          golang:1.12 \
          go build -v ./...

    - stage: test
      name: 'go'
      script: |
        docker run -it --rm \
          --workdir /src \
          --volume $PWD/go-src:/src \
          --volume /go:/go \
          golang:1.12 \
          go test -v ./...

    - stage: build docker
      name: 'hello world'
      script:
        - |
          docker build \
            --tag yarencheng/onr-tree:hello-world-latest
            --file docker/hello-world/Dockerfile \
            .
        - docker push yarencheng/onr-tree:hello-world-latest
