dist: trusty
sudo: true

cache:
  directories:
    - $HOME/go

fail_fast: true

jobs:
  include:
    - stage: build
      name: 'go'
      script: |
        docker run -it --rm \
          --workdir /src \
          --volume $PWD/go-src:/src \
          --volume /go:/go \
          golang:1.12 \
          go build -v ./...

    - stage: test
      name: 'go'
      script: |
        docker run -it --rm \
          --workdir /src \
          --volume $PWD/go-src:/src \
          --volume /go:/go \
          golang:1.12 \
          go test -v ./...

    - stage: build docker
      name: 'hello-world'
      script:
        - |
          docker build \
            --tag yarencheng/one-tree:hello-world-latest \
            --file docker/hello-world/Dockerfile \
            go-src
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push yarencheng/one-tree:hello-world-latest
