dist: trusty
sudo: true

cache:
  directories:
    - $HOME/go

jobs:
  include:
    - stage: build
      script: make build

    - stage: test
      script: make test

    - stage: images
      script:
        - make images
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push yarencheng/one-tree:hello-world-latest
        - docker push yarencheng/one-tree:kafka-producer-latest
        - docker push yarencheng/one-tree:kafka-consumergroup-latest
